In [2]:
import numpy as np

In [3]:
array1 = np.array([1,2,3,4,5])

In [4]:
print(array1)

[1 2 3 4 5]


In [5]:
array2 = np.random.rand(3, 4)

In [6]:
array2

array([[0.67912356, 0.37868123, 0.04981367, 0.69628625],
       [0.12275882, 0.7882271 , 0.21610951, 0.65082409],
       [0.50788974, 0.053135  , 0.71807013, 0.20034357]])

In [7]:
array3 = np.zeros((2, 3, 4))

In [8]:
array3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [9]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

In [10]:
addition = np.add(arr1, arr2)
subtraction = np.subtract(arr1, arr2)
multiplication = np.multiply(arr1, arr2)
division = np.divide(arr1, arr2)

In [11]:
addition

array([ 6,  8, 10, 12])

In [12]:
subtraction

array([-4, -4, -4, -4])

In [13]:
multiplication


array([ 5, 12, 21, 32])

In [14]:
division

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [15]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [16]:
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)

In [17]:
mean

5.5

In [18]:
median

5.5

In [19]:
std_dev

2.8722813232690143

In [20]:
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [21]:
array_2d = array_1d.reshape(3, 4)
array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [23]:
first_row = arr2d[0, :]
last_column = arr2d[:, -1]

In [24]:
first_row

array([1, 2, 3])

In [25]:
last_column

array([3, 6, 9])

In [26]:
ar = np.array([1, 2, 3, 4, 5])

In [27]:
reversed_arr = ar[::-1]

In [28]:
reversed_arr

array([5, 4, 3, 2, 1])

In [29]:
array2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])


In [30]:
threshold = 5

In [31]:
cond = array2d[array2d > threshold]
cond

array([6, 7, 8, 9])

In [32]:
arra = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
scalar_value = 10


In [33]:
result = arra + scalar_value
result

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [34]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = np.array([11,12,13,14,15])

In [35]:
c= a*b
c

array([[ 11,  24,  39,  56,  75],
       [ 66,  84, 104, 126, 150]])

In [36]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])


In [37]:
result =np.dot(arr1, arr2)
result

32

In [38]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
result = np.dot(array1, array2)

In [39]:
result

array([[19, 22],
       [43, 50]])

In [40]:
matrix = np.array([[50, 29], [30, 44]])

In [41]:
det = np.linalg.det(matrix) 
det

1330.0000000000002

In [42]:
inv = np.linalg.inv(matrix)

In [43]:
inv

array([[ 0.03308271, -0.02180451],
       [-0.02255639,  0.03759398]])